# Generated by Django 2.1.2 on 2019-10-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0025_auto_20191008_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'running'), ('CREATING', 'creating'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=128),
        ),
    ]
