# Generated by Django 2.1.2 on 2019-10-09 09:05

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0026_auto_20191009_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='endpoint',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='meta',
            field=common.models.JsonDictTextField(default={}),
        ),
    ]
