# Generated by Django 2.1.2 on 2019-10-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeops_api', '0027_auto_20191009_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('valid', 'valid'), ('invalid', 'invalid'), ('unknown', 'unknown')], default='unknown', max_length=128, null=True),
        ),
    ]
